name: docker-stage-example

on:
  repository_dispatch:
    types: [test-dispatch, docker-stage]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Demo Step
        run: |
          echo "This is a demo workflow"
          echo "Event type: ${{ github.event.action }}"
          echo "Version: ${{ github.event.client_payload.version }}"
          echo "Ref: ${{ github.event.client_payload.ref }}"
